os: xenial
#travis ci with python 3.7 workaround:
#ref: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
language: python
sudo: required
dist: xenial
python: "3.7"

# command to install dependencies
install:
  - apt-get install ffmpeg
  - apt-get install ffprobe
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest 
